# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PUFFIN
author: Jack Hare
email: jdhare@mit.edu
twitter: Jack_D_Hare
description: >- # this means to ignore newlines until "seo-tags:"
  PUFFIN is a new pulsed-power facility at the Plasma Science and Fusion Center (PSFC), 
  at the Massachusetts Institute of Technology (MIT). PUFFIN (the PUlser For Fundamental 
  [Plasma Physics] INvestigations) will use intense pulses of electrical current to heat 
  solids to a high-energy-density (HED) plasma state. We will use PUFFIN to carry out 
  research into fundamental plasma processes, such as magnetic reconnection and 
  magneto-hydrodynamic turbulence, which underpin events such as solar flares and 
  the transport of matter in the accretions disks of black holes.
keywords: >-
  "puffin, plasma, physics, psfc, nuclear, fusion, hed, high-energy-density, fundamental, 
  science, solar, magnetic, reconnection, turbulence, mhd, mit, massachusetts, pulsed-power,
  ltd, ltds, diagnostics"
ogimage: /assets/reconnection.png # This is the image that will display in tweets if someone links to our website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


address: 
  - PUFFIN Group,
  - Plasma Science and Fusion Center,
  - Massachusetts Institute of Technology,
  - 77 Massachusetts Ave., NW16,
  - MA 02139, USA.

# Build settings
plugins:
  - jekyll-feed

sass:
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
